apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-vplq
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-deploy-tenant/appstudio/dc-metro-map-vplq@sha256:e946274c076ad767a384c372b3b5d254d9e4cb90ee864a7320fb963e29240c8b
        name: my-nodejs
        resources: {}
status: {}
